/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sanctum/csrf-cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Planta o cookie de protecao CSRF
         * @description Primeira chamada de qualquer cliente. Devolve `204` sem corpo e planta
         *     dois cookies: `XSRF-TOKEN`, legivel pelo cliente, e o cookie de sessao.
         *
         *     O valor de `XSRF-TOKEN` chega **codificado como URL** e precisa ser
         *     decodificado antes de ir no cabecalho `X-XSRF-TOKEN`.
         *
         *     Esta rota fica fora do prefixo `/api` — ela e registrada pelo proprio
         *     Sanctum e ja chega com o middleware de sessao.
         */
        get: operations["obterCookieCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autentica e abre a sessao
         * @description Credencial invalida e recusada como **erro de validacao** (`422`), com a
         *     mensagem associada ao campo `email`. A resposta e identica para usuario
         *     inexistente e para senha incorreta: distinguir os dois transformaria a
         *     tela de autenticacao num verificador de cadastro.
         *
         *     A operacao regenera a sessao — e, com ela, o `XSRF-TOKEN`. Releia o
         *     cookie antes da proxima operacao mutante.
         */
        post: operations["autenticar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Devolve o usuario da sessao corrente
         * @description Leitura; nao exige token CSRF.
         */
        get: operations["usuarioAutenticado"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encerra a sessao
         * @description Invalida a sessao e rotaciona o identificador dela. Responde `204` sem
         *     corpo.
         */
        post: operations["encerrarSessao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista os cursos do produtor autenticado
         * @description Paginada. O recorte por proprietario acontece **na consulta**, entao
         *     `meta.total` e `meta.last_page` contam somente os cursos proprios.
         *
         *     Ordem: criacao decrescente, com o identificador como criterio de
         *     desempate para tornar a sequencia estavel entre paginas.
         */
        get: operations["listarCursos"];
        put?: never;
        /**
         * Cria um curso
         * @description O proprietario vem **da sessao**. Um `owner_id` enviado no corpo e
         *     ignorado — o campo nao existe na validacao.
         *
         *     O curso nasce em `draft` e passa a `available` sozinho na primeira
         *     publicacao de aula.
         */
        post: operations["criarCurso"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta um curso proprio */
        get: operations["obterCurso"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Arvore do curso, como o produtor a ve
         * @description Curso, modulos e aulas aninhados e ordenados por `position`.
         *
         *     **Inclui rascunhos e o estado do video de cada aula** — a jornada do
         *     produtor exige acompanhar o que ainda nao foi publicado e o que ainda
         *     esta processando. A visao equivalente do consumidor
         *     (`GET /api/catalog/courses/{course}`) nao traz nenhum dos dois.
         *
         *     Nao e paginada: a arvore e uma ordem, e paginar a ordem a quebraria.
         */
        get: operations["obterEstruturaDoCurso"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista os modulos do curso, em ordem
         * @description Colecao **nao** paginada — sai sob `data`, sem `meta` nem `links`.
         */
        get: operations["listarModulos"];
        put?: never;
        /**
         * Cria um modulo no curso
         * @description A posicao **nao** e recebida do cliente: ela e a proxima livre dentro do
         *     curso, calculada sob trava.
         */
        post: operations["criarModulo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{module}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cria uma aula no modulo
         * @description A aula nasce **em rascunho e sem video**: `published_at` e `video_state`
         *     saem nulos, e nao ha parametro capaz de mudar isso na criacao.
         */
        post: operations["criarAula"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lesson}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulta uma aula propria
         * @description `video_state` vem da tentativa atual, e nao de uma copia guardada na
         *     aula. Nulo significa que nenhum envio foi aberto ainda.
         */
        get: operations["obterAula"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lesson}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publica a aula
         * @description Exige video em `ready` **com referencia de reproducao registrada**.
         *     Falhando a condicao, a resposta e `409` com o codigo que diz qual das
         *     tres nao foi satisfeita, para a interface exibir conflito de regra em vez
         *     de erro generico.
         *
         *     Republicar uma aula ja publicada responde `200` sem efeito novo, e sem
         *     reavaliar o video. A primeira publicacao do curso o torna `available` na
         *     mesma transacao.
         */
        post: operations["publicarAula"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lesson}/video/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abre um envio de video em partes
         * @description Valida o que o cliente declara contra os limites do backend — tipo
         *     `video/mp4`, tamanho de 1 byte a 10 GiB — e abre a operacao multipart no
         *     armazenamento.
         *
         *     A resposta e o **plano de envio**: quantas partes, de que tamanho, e o
         *     identificador da tentativa. Nenhum byte e enviado nesta chamada.
         *
         *     **A chave do objeto e escolhida pelo servidor**, derivada do
         *     identificador da tentativa — nunca do nome do arquivo. O `filename`
         *     declarado e guardado apenas como informacao.
         *
         *     Um novo envio so e aceito se a tentativa atual da aula tiver terminado em
         *     `failed`; qualquer outro estado responde `409` com `VIDEO_ATTEMPT_ACTIVE`
         *     e o estado que impede como membro de extensao.
         */
        post: operations["abrirEnvioDeVideo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/video-uploads/{attempt}/parts/{part}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Emite a URL temporaria de uma parte
         * @description Devolve a URL assinada para o **navegador** enviar aquela parte direto ao
         *     armazenamento, por `PUT`, com os bytes correspondentes. Ela vale 15
         *     minutos e pode ser renovada chamando esta rota de novo — renovar nao
         *     altera nada no dominio.
         *
         *     O **primeiro** pedido move a tentativa de `pending` para `uploading`. Os
         *     seguintes nao mudam estado.
         *
         *     Numero de parte fora do plano do arquivo responde `422`; tentativa que ja
         *     encerrou o envio responde `409` com `VIDEO_UPLOAD_NOT_ACTIVE`.
         *
         *     Guarde o `ETag` que o armazenamento devolver em cada `PUT`: ele e
         *     obrigatorio na conclusao.
         */
        post: operations["emitirUrlDeParte"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/video-uploads/{attempt}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Conclui o envio e enfileira o processamento
         * @description Recebe os comprovantes de todas as partes — `part_number` e `etag`,
         *     **repassado exatamente como o armazenamento o devolveu, aspas
         *     inclusive**. Remover as aspas quebra a conclusao.
         *
         *     O backend manda o armazenamento reunir as partes e depois **observa o
         *     objeto** de forma independente: existencia, tamanho, tipo e os metadados
         *     que ele mesmo gravou na abertura. Nada disso vem do relato do cliente.
         *
         *     Quatro desfechos, e o que os separa e o **resultado da operacao**, nunca
         *     o estado em que a tentativa ficou:
         *
         *     | Situacao | Resposta |
         *     | --- | --- |
         *     | Conclusao nova e valida, com o processamento enfileirado no mesmo commit | `202` |
         *     | Repeticao de uma conclusao ja aceita | `200`, sem enfileirar de novo |
         *     | Objeto confirmadamente ausente ou incompativel, e a repeticao dessa recusa | `409` |
         *     | Conclusao pedida sobre tentativa que nao comecou a transferir | `409` |
         *     | Sem evidencia sobre o objeto — indisponibilidade, credencial, permissao | `503` |
         *
         *     A recusa e **gravada antes** de virar `409`: a tentativa fica em `failed`,
         *     que e o unico estado a partir do qual um novo envio e aceito.
         */
        post: operations["concluirEnvio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lesson}/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado da tentativa de video atual
         * @description E a rota que a interface consulta em intervalos enquanto o video esta em
         *     `uploaded` ou `processing`.
         *
         *     **Aula sem video responde `200` com `data: null`**, e nao `404`: "ainda
         *     nao enviei nada" e o estado inicial de toda aula recem-criada.
         *
         *     `failure_code` e `failure_message` sao preenchidos quando o estado e
         *     `failed`, com o mesmo texto publico que a recusa devolveu.
         */
        get: operations["obterVideoDaAula"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista os cursos concedidos ao consumidor
         * @description Duas condicoes, as duas **dentro da consulta**: o curso precisa ter
         *     concessao para o consumidor autenticado **e** estar em `available`.
         *
         *     Por isso `meta.total` conta apenas o conjunto autorizado — filtrar depois
         *     de carregar faria a contagem revelar quantos cursos existem fora da
         *     concessao.
         *
         *     Um curso concedido ainda em `draft` nao aparece aqui: nao ha nada
         *     publicado a consumir. Ele continua acessivel pelo endereco direto.
         *
         *     Consumidor sem nenhuma concessao recebe `200` com lista vazia — nao ter
         *     acesso a nada e um estado legitimo, nao um erro.
         */
        get: operations["listarCursosConcedidos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/courses/{course}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Arvore do curso concedido, so com aulas publicadas
         * @description A mesma arvore ordenada da visao do produtor, **sem rascunhos e sem
         *     estado de video**: a aula do consumidor tem cinco campos, e `video_state`
         *     nao e um deles.
         *
         *     Modulo cujas aulas estejam todas em rascunho aparece com `lessons: []` —
         *     o que o consumidor deixa de ver e o conteudo nao publicado, nao a
         *     organizacao do curso.
         *
         *     Curso sem concessao e curso inexistente respondem o **mesmo** `404`, com
         *     o mesmo corpo.
         */
        get: operations["obterEstruturaConcedida"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lesson}/playback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dados de reproducao da aula
         * @description Quatro verificacoes, nesta ordem: consumidor autenticado, concessao do
         *     curso, aula publicada, video em `ready` com referencia registrada.
         *     **A URL so e assinada depois das quatro** — nenhum caminho negativo chega
         *     ao armazenamento.
         *
         *     O retorno sao **dados de reproducao, nunca o arquivo**: uma URL `GET`
         *     pre-assinada valida por **cinco minutos**, o instante exato em que ela
         *     expira e o tipo do conteudo. Os bytes vao do armazenamento direto ao
         *     player.
         *
         *     A negativa por autorizacao e `404` e a por disponibilidade e `409` — a
         *     interface precisa separar "nao e para voce" de "ainda nao esta pronto".
         *
         *     **Limitacao assumida:** a URL funciona ate expirar e pode ser copiada.
         *     Cinco minutos reduzem, nao eliminam, a redistribuicao.
         */
        get: operations["obterReproducao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/video-processing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recebe o desfecho do processamento do video
         * @description Rota chamada por um **servico**, e nao por um navegador: nao ha sessao,
         *     nao ha perfil e **nao ha token CSRF** — a dispensa e declarada
         *     explicitamente na inicializacao da aplicacao, com o endereco escrito.
         *
         *     ## Autenticacao por assinatura
         *
         *     Duas cabecalhos obrigatorios:
         *
         *     | Cabecalho | Conteudo |
         *     | --- | --- |
         *     | `X-Webhook-Timestamp` | segundos desde a época, somente digitos |
         *     | `X-Webhook-Signature` | `v1=` seguido do HMAC em hexadecimal minusculo |
         *
         *     A assinatura e um **HMAC-SHA256** sobre a cadeia
         *     `timestamp + "." + corpo bruto`, com o segredo compartilhado, comparada
         *     em tempo constante. O corpo assinado e o **texto exato** transmitido:
         *     reserializar o JSON antes de assinar invalida a assinatura.
         *
         *     O timestamp precisa cair dentro de uma janela de **cinco minutos** em
         *     relacao ao relogio do servidor, conferida nos dois sentidos, o que limita
         *     o replay de uma assinatura capturada.
         *
         *     Assinatura ausente, malformada, incorreta ou fora da janela responde
         *     `401` — sempre a mesma resposta, sem dizer qual das quatro ocorreu.
         *
         *     ## Idempotencia
         *
         *     `event_id` e a unica chave. O primeiro desfecho definitivo vence, e
         *     qualquer reentrega dele e reconhecida **sem produzir efeito adicional** e
         *     sem que o corpo seja reavaliado.
         *
         *     ## Como responder
         *
         *     `200` significa aplicado ou ja aplicado — nao reenvie. `409` e rejeicao
         *     **permanente**: o evento nunca sera aplicado, e insistir nao muda isso.
         *     Somente `503` pede reentrega, e o cabecalho `Retry-After` diz em quantos
         *     segundos.
         */
        post: operations["receberCallbackDeProcessamento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description `draft` ate a primeira aula ser publicada; `available` a partir dai. A
         *     promocao e automatica e nao tem rota propria.
         * @enum {string}
         */
        EstadoDoCurso: "draft" | "available";
        /**
         * @description Ciclo de vida da tentativa de envio.
         *
         *     `pending` autorizado, nenhum byte ainda · `uploading` transferindo ·
         *     `uploaded` objeto verificado, processamento enfileirado · `processing`
         *     em processamento · `ready` pronto para reproduzir · `failed` encerrado
         *     com falha — o unico estado a partir do qual um novo envio e aceito.
         * @enum {string}
         */
        EstadoDoVideo: "pending" | "uploading" | "uploaded" | "processing" | "ready" | "failed";
        /**
         * @description Catalogo fechado de codigos funcionais. E este valor, e nao o texto de
         *     `detail`, que o cliente deve usar para decidir o que mostrar.
         * @enum {string}
         */
        CodigoDeFalha: "VALIDATION_FAILED" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "CSRF_TOKEN_MISMATCH" | "CONFLICT" | "VIDEO_ATTEMPT_ACTIVE" | "VIDEO_UPLOAD_NOT_ACTIVE" | "VIDEO_OBJECT_MISSING" | "VIDEO_OBJECT_MISMATCH" | "VIDEO_PROCESSING_FAILED" | "WEBHOOK_SIGNATURE_INVALID" | "WEBHOOK_EVENT_REJECTED" | "LESSON_WITHOUT_VIDEO" | "LESSON_VIDEO_NOT_READY" | "LESSON_PLAYBACK_REFERENCE_MISSING" | "LESSON_NOT_PUBLISHED" | "SERVICE_UNAVAILABLE" | "INTERNAL_ERROR";
        /** @description Corpo de erro conforme a RFC 9457, servido como `application/problem+json`. */
        Problema: {
            /**
             * Format: uri
             * @description URI do tipo, derivada do codigo funcional.
             */
            type: string;
            /** @description Titulo curto do problema. */
            title: string;
            /** @description O mesmo status da resposta HTTP. */
            status: number;
            /**
             * @description Mensagem publica, escrita para quem usa a aplicacao. Nunca carrega
             *     mensagem de excecao, consulta, caminho de arquivo nem qualquer
             *     detalhe interno.
             */
            detail: string;
            code: components["schemas"]["CodigoDeFalha"];
        };
        ProblemaDeValidacao: components["schemas"]["Problema"] & {
            errors: {
                [key: string]: string[];
            };
        };
        ProblemaDePublicacao: components["schemas"]["Problema"] & {
            video_state?: components["schemas"]["EstadoDoVideo"];
        };
        ProblemaDeEnvio: components["schemas"]["Problema"] & {
            video_state?: components["schemas"]["EstadoDoVideo"];
        };
        /** @description Exatamente quatro campos. Um quinto seria contrato novo a manter. */
        PaginacaoMeta: {
            current_page: number;
            /** @description Tamanho **efetivo** da pagina, ja limitado ao teto de 50. */
            per_page: number;
            /** @description Total do conjunto **autorizado** — nunca inclui o que o solicitante nao pode ver. */
            total: number;
            last_page: number;
        };
        /**
         * @description Os quatro links carregam o `per_page` efetivo, para que navegar pelos
         *     proprios links da API nao mude o tamanho da pagina no meio do caminho.
         */
        PaginacaoLinks: {
            /** Format: uri */
            first: string | null;
            /**
             * Format: uri
             * @description Nulo, e nao ausente, na primeira pagina.
             */
            prev: string | null;
            /**
             * Format: uri
             * @description Nulo, e nao ausente, na ultima pagina.
             */
            next: string | null;
            /** Format: uri */
            last: string | null;
        };
        Credenciais: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        /**
         * @description Quatro campos. O hash da senha nao existe nesta representacao e nunca
         *     atravessa a fronteira HTTP.
         */
        Usuario: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            /**
             * @description Cada usuario tem exatamente um perfil.
             * @enum {string}
             */
            role: "producer" | "consumer";
        };
        /** @description `owner_id` **nao** e aceito: o proprietario vem da sessao. */
        NovoCurso: {
            title: string;
            description: string;
        };
        Curso: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            /** Format: uuid */
            owner_id: string;
            state: components["schemas"]["EstadoDoCurso"];
            /**
             * Format: date-time
             * @description ISO 8601 com deslocamento explicito.
             */
            created_at: string;
        };
        /** @description `position` **nao** e aceita: ela e a proxima livre no curso. */
        NovoModulo: {
            title: string;
        };
        Modulo: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            course_id: string;
            title: string;
            position: number;
        };
        /**
         * @description `position`, `published_at` e o video **nao** sao aceitos: a posicao e
         *     calculada, e a aula nasce em rascunho e sem video.
         */
        NovaAula: {
            title: string;
        };
        /** @description A aula como o **produtor** a ve — seis campos, dois deles anulaveis. */
        Aula: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            module_id: string;
            title: string;
            position: number;
            /**
             * Format: date-time
             * @description Nulo significa rascunho. Nao existe um estado `draft` proprio.
             */
            published_at: string | null;
            /** @description Nulo quando a aula ainda nao tem tentativa de video. */
            video_state: components["schemas"]["EstadoDoVideo"] | null;
        };
        /**
         * @description A aula como o **consumidor** a ve — cinco campos. `video_state` nao
         *     existe aqui, e `published_at` nunca e nula: a arvore do consumidor nao
         *     contem rascunho.
         */
        AulaDoConsumidor: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            module_id: string;
            title: string;
            position: number;
            /** Format: date-time */
            published_at: string;
        };
        ModuloComAulas: components["schemas"]["Modulo"] & {
            /** @description Ordenadas por `position`. Vazia quando o modulo ainda nao tem aula. */
            lessons: components["schemas"]["Aula"][];
        };
        ModuloComAulasPublicadas: components["schemas"]["Modulo"] & {
            /** @description Somente aulas publicadas, ordenadas por `position`. */
            lessons: components["schemas"]["AulaDoConsumidor"][];
        };
        EstruturaDoCurso: components["schemas"]["Curso"] & {
            /** @description Ordenados por `position`. */
            modules: components["schemas"]["ModuloComAulas"][];
        };
        EstruturaDoConsumidor: components["schemas"]["Curso"] & {
            /** @description Ordenados por `position`. */
            modules: components["schemas"]["ModuloComAulasPublicadas"][];
        };
        /**
         * @description O que o cliente **declara**. Tudo e conferido contra os limites do
         *     backend, e o objeto real e observado de novo na conclusao.
         */
        AberturaDeEnvio: {
            /**
             * @description Guardado como informacao. **Nao compoe a chave de armazenamento** —
             *     ela e derivada do identificador da tentativa.
             */
            filename: string;
            /**
             * @description Unico valor aceito. Nao ha transcodificacao nesta entrega.
             * @enum {string}
             */
            content_type: "video/mp4";
            /**
             * Format: int64
             * @description Tamanho declarado em bytes. O teto e 10 GiB.
             */
            size: number;
        };
        /** @description A estrategia de transferencia que o cliente deve executar. */
        PlanoDeEnvio: {
            /**
             * Format: uuid
             * @description Identifica a tentativa nas rotas de parte e de conclusao.
             */
            attempt_id: string;
            /** @description Chave do objeto, escolhida pelo servidor. */
            storage_key: string;
            /** @description Identificador da operacao multipart, emitido pelo armazenamento. */
            upload_id: string;
            /**
             * Format: int64
             * @description Tamanho de cada parte em bytes — 64 MiB. A ultima parte pode ser menor.
             */
            part_size: number;
            /** @description Quantas partes o arquivo declarado tera. */
            part_count: number;
        };
        UrlDeParte: {
            /**
             * Format: uri
             * @description Endereco temporario para o `PUT` daquela parte, **direto ao
             *     armazenamento**. Assinada para o endereco publico.
             */
            url: string;
            /**
             * Format: date-time
             * @description Quinze minutos apos a emissao. Vencida, peca outra pela mesma rota.
             */
            expires_at: string;
        };
        ParteConcluida: {
            part_number: number;
            /**
             * @description O comprovante devolvido pelo armazenamento naquele `PUT`, repassado
             *     **exatamente como veio, aspas inclusive**.
             */
            etag: string;
        };
        ConclusaoDeEnvio: {
            parts: components["schemas"]["ParteConcluida"][];
        };
        /**
         * @description O estado do envio. **Nao expoe** chave de armazenamento, identificador
         *     multipart, tamanho verificado nem referencia de reproducao.
         */
        TentativaDeVideo: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            lesson_id: string;
            state: components["schemas"]["EstadoDoVideo"];
            /** @description O nome declarado na abertura. */
            filename: string;
            /** @description Preenchido quando `state` e `failed`. Nulo, e nao ausente, nos demais. */
            failure_code: components["schemas"]["CodigoDeFalha"] | null;
            /**
             * @description O mesmo texto publico que a recusa devolveu. Vem do catalogo fechado
             *     de falhas, nunca de uma mensagem de excecao.
             */
            failure_message: string | null;
        };
        /** @description Dados de reproducao — nunca o arquivo. */
        Reproducao: {
            /**
             * Format: uri
             * @description URL `GET` pre-assinada, valida por cinco minutos.
             */
            playback_url: string;
            /**
             * Format: date-time
             * @description Quando a URL deixa de funcionar. Acompanha a URL para o player poder
             *     renovar antes de o armazenamento recusar no meio da reproducao.
             */
            expires_at: string;
            /**
             * @description O tipo observado no objeto durante a conclusao do envio.
             * @example video/mp4
             */
            content_type: string;
        };
        /**
         * @description Exatamente quatro campos. As duas exigencias cruzadas sao recusa ativa, e
         *     nao tolerancia: `playback_reference` e **obrigatoria** com `ready` e
         *     **proibida** com `failed`.
         */
        CargaDoCallback: {
            /** @description Unica chave de idempotencia. O primeiro desfecho definitivo vence. */
            event_id: string;
            /**
             * Format: uuid
             * @description Identificador da tentativa. Um valor que nao e UUID e carga
             *     malformada (`422`); um UUID bem formado que nao corresponde a
             *     tentativa alguma e rejeicao permanente (`409`).
             */
            video_id: string;
            /** @enum {string} */
            status: "ready" | "failed";
            /**
             * @description Obrigatoria quando `status` e `ready`; proibida quando e `failed`.
             *     E ela — e nao uma chave remontada — que a reproducao assina depois.
             */
            playback_reference?: string | null;
        };
        EventoAplicado: {
            event_id: string;
            /**
             * @description `accepted` — o desfecho foi aplicado ao video.
             *     `rejected_permanent` acompanha o `409`, e nao esta corpo.
             * @enum {string}
             */
            outcome: "accepted" | "rejected_permanent";
        };
        UsuarioEnvelope: {
            data: components["schemas"]["Usuario"];
        };
        CursoEnvelope: {
            data: components["schemas"]["Curso"];
        };
        ModuloEnvelope: {
            data: components["schemas"]["Modulo"];
        };
        /** @description Colecao sem paginacao — sem `meta` e sem `links`. */
        ModulosEnvelope: {
            data: components["schemas"]["Modulo"][];
        };
        AulaEnvelope: {
            data: components["schemas"]["Aula"];
        };
        EstruturaEnvelope: {
            data: components["schemas"]["EstruturaDoCurso"];
        };
        EstruturaDoConsumidorEnvelope: {
            data: components["schemas"]["EstruturaDoConsumidor"];
        };
        CursosPaginados: {
            data: components["schemas"]["Curso"][];
            meta: components["schemas"]["PaginacaoMeta"];
            links: components["schemas"]["PaginacaoLinks"];
        };
        PlanoEnvelope: {
            data: components["schemas"]["PlanoDeEnvio"];
        };
        UrlDeParteEnvelope: {
            data: components["schemas"]["UrlDeParte"];
        };
        TentativaEnvelope: {
            data: components["schemas"]["TentativaDeVideo"];
        };
        /** @description `data` e `null` quando a aula ainda nao tem tentativa de video. */
        TentativaOuNuloEnvelope: {
            data: components["schemas"]["TentativaDeVideo"] | null;
        };
        ReproducaoEnvelope: {
            data: components["schemas"]["Reproducao"];
        };
        EventoAplicadoEnvelope: {
            data: components["schemas"]["EventoAplicado"];
        };
    };
    responses: {
        /**
         * @description Sem sessao valida. E um estado proprio na interface, distinto de acesso
         *     negado: reconduz a autenticacao.
         */
        NaoAutenticado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /**
         * @description Autenticado, **perfil errado para a rota**. Um produtor nas rotas de
         *     consumo, ou um consumidor nas de gestao — inclusive o produtor dono do
         *     recurso, porque ser dono nao e ser consumidor.
         *
         *     Nao confundir com `404`: aqui nada e revelado sobre nenhum recurso.
         */
        PerfilNegado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /**
         * @description Recurso inexistente, de outro produtor, ou curso sem concessao —
         *     **resposta identica nos tres casos**, com o mesmo corpo. Comparar as
         *     respostas nao permite descobrir se o identificador existe.
         *
         *     Tambem e o que um identificador malformado recebe: o roteador o recusa
         *     antes de a aplicacao rodar.
         */
        NaoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /**
         * @description Token de protecao ausente ou incorreto. **A operacao nao foi executada.**
         *
         *     Tratamento correto: obter um token novo em `GET /sanctum/csrf-cookie` — ou
         *     reler o cookie `XSRF-TOKEN`, que o login regenera — e repetir a
         *     requisicao **uma vez**. Nao e falha de autenticacao, e a sessao continua
         *     valida.
         */
        TokenCsrfInvalido: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description Entrada invalida, com o detalhamento por campo em `errors`. */
        ValidacaoFalhou: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemaDeValidacao"];
            };
        };
        /**
         * @description Falha inesperada. A resposta e **sempre a mesma**, inclusive com
         *     depuracao ligada: nada do erro original — mensagem, classe, arquivo,
         *     linha, consulta ou pilha — atravessa esta fronteira. O registro completo
         *     vai para o log.
         */
        ErroInterno: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
    };
    parameters: {
        /** @description Identificador do curso. */
        CursoId: string;
        /** @description Identificador do modulo. */
        ModuloId: string;
        /** @description Identificador da aula. */
        AulaId: string;
        /** @description Identificador da tentativa de envio, devolvido pela abertura. */
        TentativaId: string;
        /**
         * @description Numero da parte, a partir de 1. O roteador so aceita digitos: um valor
         *     nao numerico recebe `404` antes de qualquer codigo da aplicacao rodar.
         */
        NumeroDaParte: number;
        /** @description Pagina desejada, a partir de 1. */
        Pagina: number;
        /**
         * @description Itens por pagina. Ausente vale 15.
         *
         *     Valores **acima de 50 sao atendidos e limitados a 50**, e nao recusados:
         *     a intencao de quem pede o maximo e legitima, e o teto existe para
         *     proteger a resposta. Zero, negativo ou nao inteiro sao `422` — nao existe
         *     pagina de tamanho zero, e escolher um padrao no lugar do valor invalido
         *     esconderia o engano de quem chamou.
         *
         *     `meta.per_page` sempre devolve o tamanho **efetivo**.
         */
        PorPagina: number;
        /**
         * @description Valor do cookie `XSRF-TOKEN`, **decodificado de URL**. Obtido em
         *     `GET /sanctum/csrf-cookie` e renovado pelo login, que regenera a sessao.
         */
        TokenCsrf: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    obterCookieCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cookies plantados. Sem corpo. */
            204: {
                headers: {
                    /** @description `XSRF-TOKEN` e o cookie de sessao. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    autenticar: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Valor do cookie `XSRF-TOKEN`, **decodificado de URL**. Obtido em
                 *     `GET /sanctum/csrf-cookie` e renovado pelo login, que regenera a sessao.
                 */
                "X-XSRF-TOKEN": components["parameters"]["TokenCsrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credenciais"];
            };
        };
        responses: {
            /** @description Sessao aberta. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioEnvelope"];
                };
            };
            419: components["responses"]["TokenCsrfInvalido"];
            /** @description Campos ausentes ou credencial recusada. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemaDeValidacao"];
                };
            };
            500: components["responses"]["ErroInterno"];
        };
    };
    usuarioAutenticado: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O usuario autenticado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioEnvelope"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            500: components["responses"]["ErroInterno"];
        };
    };
    encerrarSessao: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Valor do cookie `XSRF-TOKEN`, **decodificado de URL**. Obtido em
                 *     `GET /sanctum/csrf-cookie` e renovado pelo login, que regenera a sessao.
                 */
                "X-XSRF-TOKEN": components["parameters"]["TokenCsrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessao encerrada. Sem corpo. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NaoAutenticado"];
            419: components["responses"]["TokenCsrfInvalido"];
            500: components["responses"]["ErroInterno"];
        };
    };
    listarCursos: {
        parameters: {
            query?: {
                /** @description Pagina desejada, a partir de 1. */
                page?: components["parameters"]["Pagina"];
                /**
                 * @description Itens por pagina. Ausente vale 15.
                 *
                 *     Valores **acima de 50 sao atendidos e limitados a 50**, e nao recusados:
                 *     a intencao de quem pede o maximo e legitima, e o teto existe para
                 *     proteger a resposta. Zero, negativo ou nao inteiro sao `422` — nao existe
                 *     pagina de tamanho zero, e escolher um padrao no lugar do valor invalido
                 *     esconderia o engano de quem chamou.
                 *
                 *     `meta.per_page` sempre devolve o tamanho **efetivo**.
                 */
                per_page?: components["parameters"]["PorPagina"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pagina de cursos proprios. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursosPaginados"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            422: components["responses"]["ValidacaoFalhou"];
            500: components["responses"]["ErroInterno"];
        };
    };
    criarCurso: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Valor do cookie `XSRF-TOKEN`, **decodificado de URL**. Obtido em
                 *     `GET /sanctum/csrf-cookie` e renovado pelo login, que regenera a sessao.
                 */
                "X-XSRF-TOKEN": components["parameters"]["TokenCsrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NovoCurso"];
            };
        };
        responses: {
            /** @description Curso criado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursoEnvelope"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            419: components["responses"]["TokenCsrfInvalido"];
            422: components["responses"]["ValidacaoFalhou"];
            500: components["responses"]["ErroInterno"];
        };
    };
    obterCurso: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador do curso. */
                course: components["parameters"]["CursoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O curso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursoEnvelope"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            404: components["responses"]["NaoEncontrado"];
            500: components["responses"]["ErroInterno"];
        };
    };
    obterEstruturaDoCurso: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador do curso. */
                course: components["parameters"]["CursoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A arvore completa. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstruturaEnvelope"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            404: components["responses"]["NaoEncontrado"];
            500: components["responses"]["ErroInterno"];
        };
    };
    listarModulos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador do curso. */
                course: components["parameters"]["CursoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Modulos ordenados por `position`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModulosEnvelope"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            404: components["responses"]["NaoEncontrado"];
            500: components["responses"]["ErroInterno"];
        };
    };
    criarModulo: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Valor do cookie `XSRF-TOKEN`, **decodificado de URL**. Obtido em
                 *     `GET /sanctum/csrf-cookie` e renovado pelo login, que regenera a sessao.
                 */
                "X-XSRF-TOKEN": components["parameters"]["TokenCsrf"];
            };
            path: {
                /** @description Identificador do curso. */
                course: components["parameters"]["CursoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NovoModulo"];
            };
        };
        responses: {
            /** @description Modulo criado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuloEnvelope"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            404: components["responses"]["NaoEncontrado"];
            419: components["responses"]["TokenCsrfInvalido"];
            422: components["responses"]["ValidacaoFalhou"];
            500: components["responses"]["ErroInterno"];
        };
    };
    criarAula: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Valor do cookie `XSRF-TOKEN`, **decodificado de URL**. Obtido em
                 *     `GET /sanctum/csrf-cookie` e renovado pelo login, que regenera a sessao.
                 */
                "X-XSRF-TOKEN": components["parameters"]["TokenCsrf"];
            };
            path: {
                /** @description Identificador do modulo. */
                module: components["parameters"]["ModuloId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NovaAula"];
            };
        };
        responses: {
            /** @description Aula criada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AulaEnvelope"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            404: components["responses"]["NaoEncontrado"];
            419: components["responses"]["TokenCsrfInvalido"];
            422: components["responses"]["ValidacaoFalhou"];
            500: components["responses"]["ErroInterno"];
        };
    };
    obterAula: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da aula. */
                lesson: components["parameters"]["AulaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A aula. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AulaEnvelope"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            404: components["responses"]["NaoEncontrado"];
            500: components["responses"]["ErroInterno"];
        };
    };
    publicarAula: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Valor do cookie `XSRF-TOKEN`, **decodificado de URL**. Obtido em
                 *     `GET /sanctum/csrf-cookie` e renovado pelo login, que regenera a sessao.
                 */
                "X-XSRF-TOKEN": components["parameters"]["TokenCsrf"];
            };
            path: {
                /** @description Identificador da aula. */
                lesson: components["parameters"]["AulaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aula publicada — ou ja publicada, sem efeito novo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AulaEnvelope"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            404: components["responses"]["NaoEncontrado"];
            /**
             * @description A condicao de publicacao nao foi satisfeita. O `code` distingue os
             *     tres motivos, e `video_state` acompanha o problema como membro de
             *     extensao para a interface nao precisar de uma segunda requisicao.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemaDePublicacao"];
                };
            };
            419: components["responses"]["TokenCsrfInvalido"];
            500: components["responses"]["ErroInterno"];
        };
    };
    abrirEnvioDeVideo: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Valor do cookie `XSRF-TOKEN`, **decodificado de URL**. Obtido em
                 *     `GET /sanctum/csrf-cookie` e renovado pelo login, que regenera a sessao.
                 */
                "X-XSRF-TOKEN": components["parameters"]["TokenCsrf"];
            };
            path: {
                /** @description Identificador da aula. */
                lesson: components["parameters"]["AulaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AberturaDeEnvio"];
            };
        };
        responses: {
            /** @description Envio aberto. O plano diz em quantas partes transferir. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanoEnvelope"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            404: components["responses"]["NaoEncontrado"];
            /** @description A aula ja tem uma tentativa que nao terminou em falha. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemaDeEnvio"];
                };
            };
            419: components["responses"]["TokenCsrfInvalido"];
            /** @description Tipo nao aceito, tamanho fora dos limites ou campo ausente. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemaDeValidacao"];
                };
            };
            500: components["responses"]["ErroInterno"];
        };
    };
    emitirUrlDeParte: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Valor do cookie `XSRF-TOKEN`, **decodificado de URL**. Obtido em
                 *     `GET /sanctum/csrf-cookie` e renovado pelo login, que regenera a sessao.
                 */
                "X-XSRF-TOKEN": components["parameters"]["TokenCsrf"];
            };
            path: {
                /** @description Identificador da tentativa de envio, devolvido pela abertura. */
                attempt: components["parameters"]["TentativaId"];
                /**
                 * @description Numero da parte, a partir de 1. O roteador so aceita digitos: um valor
                 *     nao numerico recebe `404` antes de qualquer codigo da aplicacao rodar.
                 */
                part: components["parameters"]["NumeroDaParte"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description URL temporaria da parte. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlDeParteEnvelope"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            404: components["responses"]["NaoEncontrado"];
            /** @description O envio ja foi encerrado e nao aceita mais partes. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            419: components["responses"]["TokenCsrfInvalido"];
            422: components["responses"]["ValidacaoFalhou"];
            500: components["responses"]["ErroInterno"];
        };
    };
    concluirEnvio: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Valor do cookie `XSRF-TOKEN`, **decodificado de URL**. Obtido em
                 *     `GET /sanctum/csrf-cookie` e renovado pelo login, que regenera a sessao.
                 */
                "X-XSRF-TOKEN": components["parameters"]["TokenCsrf"];
            };
            path: {
                /** @description Identificador da tentativa de envio, devolvido pela abertura. */
                attempt: components["parameters"]["TentativaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConclusaoDeEnvio"];
            };
        };
        responses: {
            /**
             * @description Conclusao **ja** aceita numa chamada anterior. Nenhum processamento
             *     novo foi enfileirado. O estado pode ser `uploaded`, `processing` ou
             *     `ready`, conforme o quanto ja avancou.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TentativaEnvelope"];
                };
            };
            /** @description Conclusao aceita **agora**; processamento enfileirado. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TentativaEnvelope"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            404: components["responses"]["NaoEncontrado"];
            /**
             * @description Conclusao recusada. `VIDEO_OBJECT_MISSING` e `VIDEO_OBJECT_MISMATCH`
             *     deixam a tentativa em `failed` e liberam um novo envio;
             *     `VIDEO_UPLOAD_NOT_ACTIVE` sobre uma tentativa em `pending` nao toca no
             *     armazenamento.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            419: components["responses"]["TokenCsrfInvalido"];
            422: components["responses"]["ValidacaoFalhou"];
            500: components["responses"]["ErroInterno"];
            /**
             * @description Sem evidencia sobre o objeto. A tentativa **permanece** em
             *     `uploading` e a conclusao pode ser repetida.
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    obterVideoDaAula: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da aula. */
                lesson: components["parameters"]["AulaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A tentativa atual, ou `null` se a aula ainda nao tem video. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TentativaOuNuloEnvelope"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            404: components["responses"]["NaoEncontrado"];
            500: components["responses"]["ErroInterno"];
        };
    };
    listarCursosConcedidos: {
        parameters: {
            query?: {
                /** @description Pagina desejada, a partir de 1. */
                page?: components["parameters"]["Pagina"];
                /**
                 * @description Itens por pagina. Ausente vale 15.
                 *
                 *     Valores **acima de 50 sao atendidos e limitados a 50**, e nao recusados:
                 *     a intencao de quem pede o maximo e legitima, e o teto existe para
                 *     proteger a resposta. Zero, negativo ou nao inteiro sao `422` — nao existe
                 *     pagina de tamanho zero, e escolher um padrao no lugar do valor invalido
                 *     esconderia o engano de quem chamou.
                 *
                 *     `meta.per_page` sempre devolve o tamanho **efetivo**.
                 */
                per_page?: components["parameters"]["PorPagina"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pagina de cursos concedidos e disponiveis. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursosPaginados"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            422: components["responses"]["ValidacaoFalhou"];
            500: components["responses"]["ErroInterno"];
        };
    };
    obterEstruturaConcedida: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador do curso. */
                course: components["parameters"]["CursoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A arvore publicada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstruturaDoConsumidorEnvelope"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            404: components["responses"]["NaoEncontrado"];
            500: components["responses"]["ErroInterno"];
        };
    };
    obterReproducao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da aula. */
                lesson: components["parameters"]["AulaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados de reproducao. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReproducaoEnvelope"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["PerfilNegado"];
            404: components["responses"]["NaoEncontrado"];
            /**
             * @description A aula esta dentro de um curso concedido, mas nao ha o que
             *     reproduzir. `LESSON_NOT_PUBLISHED` cobre a aula em rascunho;
             *     `LESSON_VIDEO_NOT_READY` cobre aula publicada sem tentativa atual,
             *     com tentativa fora de `ready`, ou pronta sem referencia registrada.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            500: components["responses"]["ErroInterno"];
            /**
             * @description A autorizacao passou, mas **a assinatura da URL falhou** —
             *     credencial, configuracao ou indisponibilidade do armazenamento.
             *
             *     Nada da falha original atravessa: nem a excecao, nem o provedor, nem
             *     a chave do objeto. Quem chamou recebe a mesma indisponibilidade
             *     temporaria de qualquer outro erro de infraestrutura, e pode repetir a
             *     requisicao.
             *
             *     **Sem `Retry-After`.** O cabecalho e emitido pelo callback de
             *     processamento, que tem politica de reentrega declarada; aqui quem
             *     repete e uma pessoa diante de um player, e nao um servico.
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    receberCallbackDeProcessamento: {
        parameters: {
            query?: never;
            header: {
                /** @description Segundos desde a época, somente digitos. */
                "X-Webhook-Timestamp": string;
                /**
                 * @description `v1=` seguido do HMAC-SHA256 em hexadecimal minusculo. O exemplo e um
                 *     preenchimento de zeros: ele tem o formato certo e **nao** e uma
                 *     assinatura valida para carga nenhuma.
                 */
                "X-Webhook-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CargaDoCallback"];
            };
        };
        responses: {
            /**
             * @description Evento aplicado, ou reentrega de um evento ja concluido — nos dois
             *     casos o desfecho armazenado e o que a resposta repete.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoAplicadoEnvelope"];
                };
            };
            /**
             * @description Assinatura ausente, malformada, incorreta ou fora da janela de cinco
             *     minutos. Resposta identica nos quatro casos, e nenhum efeito e
             *     produzido.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            /**
             * @description Rejeicao **permanente**, registrada. O evento e incompativel com o
             *     estado atual, ou aponta para uma tentativa que nao existe. Nao
             *     reenvie.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            /**
             * @description Carga estruturalmente invalida — `status` fora do par aceito,
             *     `video_id` que nao e UUID, `playback_reference` ausente num `ready`
             *     ou presente num `failed`.
             *
             *     A recusa acontece **antes** de qualquer reserva de idempotencia: um
             *     emissor com defeito nao consome o `event_id`, e a reentrega da carga
             *     corrigida e avaliada normalmente.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemaDeValidacao"];
                };
            };
            500: components["responses"]["ErroInterno"];
            /**
             * @description Falha transitoria ao registrar o evento. **Nada foi gravado** e o
             *     estado atual foi preservado; a reentrega do mesmo `event_id` sera
             *     avaliada do zero.
             */
            503: {
                headers: {
                    /** @description Em quantos segundos reenviar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
}
